### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by MSadeghzadehG** [aut-ce/harpocrates#7]
It seems there is no more more_grades.py file and maybe the logic has been changed.

**Comment by MSadeghzadehG** [comment]
@1995parham

**Comment by 1995parham** [comment]
Yeah, you are right. I will fix it.

**Comment by 1995parham** [comment]
I have updated README.md, please check it. 🙌

**Comment by MSadeghzadehG** [comment]
Seems ok.
